export const actionTypes = {
    ADD_PARTICIPANT: 'ADD_PARTICIPANT',
    SHOW_WINNER: 'SHOW_WINNER',
    DELETE_PARTICIPANT: 'DELETE_PARTICIPANT',
    FILTER: 'FILTER',
    OPEN_TIMER: 'OPEN_TIMER',
    SET_CURRENT_PATICIPANT: 'SET_CURRENT_PATICIPANT',
};