export const actionTypes = {
    CREATE_CONTEST: 'CREATE_CONTEST',
    ADD_PARTICIPANT: 'ADD_PARTICIPANT',
    SHOW_WINNER: 'SHOW_WINNER',
    DELETE_PARTICIPANT: 'DELETE_PARTICIPANT',
    FILTER: 'FILTER',
    CONTESTS_FILTER: 'CONTESTS_FILTER',
    OPEN_TIMER: 'OPEN_TIMER',
    SET_CURRENT_PATICIPANT: 'SET_CURRENT_PATICIPANT',

};