export const actionTypes = {
    CREATE_CONTEST: 'CREATE_CONTEST',
    ADD_PARTICIPANT: 'ADD_PARTICIPANT',
    SHOW_WINNER: 'SHOW_WINNER',
    DELETE_PARTICIPANT: 'DELETE_PARTICIPANT',
    FILTER_PARTICIPANT: 'FILTER_PARTICIPANT',
    CONTESTS_FILTER: 'CONTESTS_FILTER',
    OPEN_TIMER: 'OPEN_TIMER',
    SET_CURRENT_PATICIPANT: 'SET_CURRENT_PATICIPANT',
    SET_CURRENT_CONTEST: 'SET_CURRENT_CONTEST',
    SAVE_TO_LOCALSTORAGE: 'SAVE_TO_LOCALSTORAGE',
    REOPEN_COMPETITION: 'REOPEN_COMPETITION',
    DELETE_CONTEST: 'DELETE_CONTEST',
};